### ISSUE TITLE
[bug] Fragment 전환 오류

### ISSUE THREAD

**Issue by LeeJeongHwi** [ITs-smu-Team/its-frontend-android#1]
![image](https://user-images.githubusercontent.com/55193363/118936015-1b057c80-b987-11eb-8077-c99f741d3967.png)

![image](https://user-images.githubusercontent.com/55193363/118936058-25277b00-b987-11eb-833e-f972e09b2596.png)

가이드 북에 들어갔다오면 다음과 같이 프래그먼트 전환에러가 발생함

**Comment by LeeJeongHwi** [comment]
해결완료

**Comment by jhlsuper** [comment]
고쳐진거같다!! 확인점!
